### ISSUE TITLE
Dusk and dawn switched?

### ISSUE THREAD

**Issue by glentennis** [marcospoel/dusk_dawn#1]
https://github.com/marcospoel/dusk_dawn/blob/f65636198988fb21617ec8838716335099fce775/dusk_dawn.py#L122

Hi, I was taking a look at this code, and I think you have dusk and dawn switched here! Should it instead be this?

```
    if result_lowest == "next_twilight_rise_utc":
        result="night"
    elif result_lowest == "next_sunrise_utc":
        result = "dawn"
    elif result_lowest == "next_sunset_utc":
        result = "day"
    elif result_lowest == "next_twilight_set_utc":
        result = "dusk"
```

**Comment by marcospoel** [comment]
Uffff, yes, and I'm ashamed of myself. You are right.
